index index.php index.html;
charset utf-8;

location / {
    try_files $uri $uri/ /index.php$is_args$args;
}

location ~ \.php$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param REDIRECT_STATUS 200;
    fastcgi_pass $php_server:9000;
    try_files $uri =404;
}

location ~ /\.(?!well-known).* {
    deny all;
}